export const list = {
  Leads: {
    saveApi: "/leads",
    getApi: "/search-leads",
    updateApi: "/leads",
    detailApi: "/leads-get-by-id/",
    filterApi: "/get-leads-filter-field",
    tableHeaderApi: "/views-get-by-title/Leads",
    formApi: "/forms-get-by-title/Leads",
    btnText: "Create Lead",
    detialUrl: "/crm/lead-details/",
    cloneUrl: "/crm/lead-clone/",
    redirectUrl: "/crm/leads",
    deleteUrl: "leads-mass-delete",
    transferUrl: "leads-mass-transfer",
    massUpdateUrl: "leads-mass-update",
    excelUrl: "add-leads-excel",
  },
  Contacts: {
    saveApi: "/contacts",
    getApi: "/search-contacts",
    updateApi: "/contacts",
    detailApi: "/contacts-get-by-id/",
    detailnameApi: "/contacts-get-by-name/",
    filterApi: "/get-contacts-filter-field",
    tableHeaderApi: "/views-get-by-title/Contacts",
    formApi: "/forms-get-by-title/Contacts",
    detialUrl: "/crm/contacts-details/",
    cloneUrl: "/crm/contacts-clone/",
    redirectUrl: "/crm/contacts",
    deleteUrl: "contacts-mass-delete",
    transferUrl: "contacts-mass-transfer",
    massUpdateUrl: "contacts-mass-update",
    excelUrl: "add-contacts-excel",
  },
  Accounts: {
    saveApi: "/accounts",
    getApi: "/search-accounts",
    updateApi: "/accounts",
    detailApi: "/accounts-get-by-id/",
    filterApi: "/get-accounts-filter-field",
    tableHeaderApi: "/views-get-by-title/Accounts",
    formApi: "/forms-get-by-title/Accounts",
    detialUrl: "/crm/account-details/",
    cloneUrl: "/crm/account-clone/",
    redirectUrl: "/crm/accounts",
    deleteUrl: "account-mass-delete",
    transferUrl: "account-mass-transfer",
    massUpdateUrl: "account-mass-update",
    excelUrl: "add-accounts-excel",
  },
  Opportunities: {
    saveApi: "/deals",
    getApi: "/search-deals",
    updateApi: "/deals",
    detailApi: "/deals-get-by-id/",
    filterApi: "/get-deals-filter-field",
    tableHeaderApi: "/views-get-by-title/Opportunities",
    formApi: "/forms-get-by-title/Opportunities",
    detialUrl: "/crm/opportunities-details/",
    cloneUrl: "/crm/opportunities-clone/",
    ownerName: "OpportunityName",
    redirectUrl: "/crm/opportunities",
    deleteUrl: "deals-mass-delete",
    transferUrl: "deals-mass-transfer",
    massUpdateUrl: "deals-mass-update",
    excelUrl: "add-deal-excel",
  },
  Tasks: {
    saveApi: "/tasks",
    getApi: "/search-tasks",
    updateApi: "/tasks",
    detailApi: "/tasks-get-by-id/",
    filterApi: "/get-tasks-filter-field",
    tableHeaderApi: "/views-get-by-title/Tasks",
    formApi: "/forms-get-by-title/Tasks",
    detialUrl: "/crm/task-details/",
    cloneUrl: "/crm/task-clone/",
    redirectUrl: "/crm/tasks",
    deleteUrl: "tasks-mass-delete",
    transferUrl: "tasks-mass-transfer",
    massUpdateUrl: "tasks-mass-update",
    excelUrl: "add-tasks-excel",
  },

  Meeting: {
    saveApi: "/meetings",
    getApi: "/search-meetings",
    updateApi: "/meetings",
    detailApi: "/meetings-get-by-id/",
    filterApi: "/get-meetings-filter-field",
    tableHeaderApi: "/views-get-by-title/Meeting",
    formApi: "/forms-get-by-title/Meeting",
    detialUrl: "/crm/meeting-details/",
    cloneUrl: "/crm/meeting-clone/",
    redirectUrl: "/crm/meeting",
    deleteUrl: "meetings-mass-delete",
    transferUrl: "meetings-mass-transfer",
    massUpdateUrl: "meetings-mass-update",
    excelUrl: "add-meetings-excel",
  },

  //Create Calls

  Calls: {
    saveApi: "/calls",
    getApi: "/search-calls",
    updateApi: "/calls",
    detailApi: "/calls-get-by-id/",
    filterApi: "/get-calls-filter-field",
    tableHeaderApi: "/views-get-by-title/Calls",
    formApi: "/forms-get-by-title/Calls",
    detialUrl: "/crm/call-details/",
    cloneUrl: "/crm/call-clone/",
    redirectUrl: "/crm/call",
    deleteUrl: "call-mass-delete",
    transferUrl: "call-mass-transfer",
    massUpdateUrl: "call-mass-update",
    excelUrl: "add-call-excel",
  },

  //Sms
  Sms: {
    saveApi: "/add-sms-temp",
    getApi: "/search-get-sms-temp",
    updateApi: "/update-sms-temp",
    detailApi: "/sms-get-by-id/",
    filterApi: "/get-sms-filter-field",
    tableHeaderApi: "/views-get-by-title/Sms",
    formApi: "/forms-get-by-title/Sms",
    detialUrl: "/crm/sms-details/",
    cloneUrl: "/crm/sms-clone/",

    redirectUrl: "/crm/sms",
  },

  //Email
  Email: {
    saveApi: "/add-email-temp",
    getApi: "/search-get-email-temp",
    updateApi: "/update-email-temp",
    detailApi: "/email-get-by-id/",
    filterApi: "/get-email-filter-field",
    tableHeaderApi: "/views-get-by-title/Email",
    formApi: "/forms-get-by-title/Email",
    detialUrl: "/crm/email-details/",
    cloneUrl: "/crm/email-clone/",
    redirectUrl: "/crm/email",
  },

  Whatsapp: {
    saveApi: "/add-whatsapp-temp",
    getApi: "/search-get-whatsapp-temp",
    updateApi: "/update-whatsapp-temp",
    detailApi: "/whatsapp-get-by-id/",
    filterApi: "/get-whatsapp-filter-field",
    tableHeaderApi: "/views-get-by-title/WhatsappTemplate",
    formApi: "/forms-get-by-title/Whatsapp",
    detialUrl: "/crm/Whatsapp-details/",
    cloneUrl: "/crm/whatsapp-clone/",
    redirectUrl: "/crm/whatsapp",
  },

  siteVisit: {
    saveApi: "/siteVisit",
    getApi: "/search-siteVisit",
    updateApi: "/siteVisit",
    detailApi: "/siteVisit-get-by-id/",
    filterApi: "/get-siteVisit-filter-field",
    tableHeaderApi: "/views-get-by-title/siteVisit",
    formApi: "/forms-get-by-title/siteVisit",
    detialUrl: "/crm/SiteVisit-details/",
    cloneUrl: "/crm/SiteVisit-clone/",
    redirectUrl: "/crm/sitevisit",
    deleteUrl: "siteVisit-mass-delete",
    transferUrl: "siteVisit-mass-transfer",
    massUpdateUrl: "siteVisit-mass-update",
    excelUrl: "add-siteVisit-excel",
  },
  Inventory: {
    saveApi: "/inventory",
    getApi: "/search-inventory",
    updateApi: "/inventory",
    detailApi: "/inventory-get-by-id/",
    filterApi: "/get-inventory-filter-field",
    tableHeaderApi: "/views-get-by-title/Inventory",
    formApi: "/forms-get-by-title/Inventory",
    detialUrl: "/crm/inventory-detail/",
    cloneUrl: "/crm/inventory-clone/",
    redirectUrl: "/crm/inventory",
    deleteUrl: "inventory-mass-delete",
    transferUrl: "inventory-mass-transfer",
    massUpdateUrl: "inventory-mass-update",
    excelUrl: "add-inventory-excel",
  },
  Note: {
    saveApi: "/notes",
    getApi: "/search-notes",
    updateApi: "/notes",
    detailApi: "/notes-get-by-id/",
    filterApi: "/get-notes-filter-field",
    tableHeaderApi: "/views-get-by-title/Note",
    formApi: "/forms-get-by-title/Note",
    detialUrl: "/crm/note-detail/",
    cloneUrl: "/crm/notes-clone/",
    redirectUrl: "/crm/notes",
    deleteUrl: "notes-mass-delete",
    transferUrl: "notes-mass-transfer",
    massUpdateUrl: "notes-mass-update",
    excelUrl: "add-notes-excel",
  },
  Quotes: {
    saveApi: "/quotes",
    getApi: "/search-quotes",
    updateApi: "/quotes",
    detailApi: "/quotes-get-by-id/",
    filterApi: "/get-quotes-filter-field",
    tableHeaderApi: "/views-get-by-title/Quotes",
    formApi: "/forms-get-by-title/Quotes",
    detialUrl: "/crm/quotes-details/",
    cloneUrl: "/crm/quotes-clone/",
    redirectUrl: "/crm/quotes",
    deleteUrl: "quotes-mass-delete",
    transferUrl: "quotes-mass-transfer",
    massUpdateUrl: "quotes-mass-update",
    excelUrl: "add-quotes-excel",
  },
  Invoice: {
    saveApi: "/invoices",
    getApi: "/search-invoices",
    updateApi: "/invoices",
    detailApi: "/invoices-get-by-id/",
    filterApi: "/get-invoices-filter-field",
    tableHeaderApi: "/views-get-by-title/Invoice",
    formApi: "/forms-get-by-title/Invoice",
    detialUrl: "/crm/invoices-details/",
    cloneUrl: "/crm/invoices-clone/",
    redirectUrl: "/crm/invoices",
    deleteUrl: "invoices-mass-delete",
    transferUrl: "invoices-mass-transfer",
    massUpdateUrl: "invoices-mass-update",
    excelUrl: "add-invoices-excel",
  },
  salesOrder: {
    saveApi: "/sale-orders",
    // getApi: "/sale-orders-by-connection/:connectionId",
    getApi: "/search-sale-orders",
    updateApi: "/sale-orders/:id",
    detailApi: "/sale-orders-get-by-id/:id",
    filterApi: "/get-sale-orders-filter-field",
    tableHeaderApi: "/views-get-by-title/salesOrder",
    formApi: "/forms-get-by-title/salesOrder",
    detialUrl: "/crm/saleOrder-details/",
    cloneUrl: "/crm/salesOrder-clone/",
    redirectUrl: "/crm/search-sale-orders",
    deleteUrl: "salesOrder-mass-delete",
    transferUrl: "salesOrder-mass-transfer",
    massUpdateUrl: "salesOrder-mass-update",
    excelUrl: "add-saleOrder-excel",
  },
  Vendor: {
    saveApi: "/vendor",
    getApi: "/search-vendor",
    updateApi: "/vendor",
    detailApi: "/vendor-get-by-id/",
    filterApi: "/get-vendor-filter-field",
    tableHeaderApi: "/views-get-by-title/vendor",
    formApi: "/forms-get-by-title/Vendor",
    detialUrl: "/crm/vendor-details/",
    cloneUrl: "/crm/vendor-clone/",
    redirectUrl: "/crm/vendor",
    deleteUrl: "vendor-mass-delete",
    transferUrl: "vendor-mass-transfer",
    massUpdateUrl: "vendor-mass-update",
    excelUrl: "add-vendor-excel",
  },
  channelPartner: {
    saveApi: "/channel-partner",
    getApi: "/search-channel-partner",
    updateApi: "/channel-partner",
    detailApi: "/channel-partner-get-by-id/",
    filterApi: "/get-channel-partner-filter-field",
    tableHeaderApi: "/views-get-by-title/channelPartner",
    formApi: "/forms-get-by-title/channelPartner",
    detialUrl: "/crm/channelPartner-details/",
    cloneUrl: "/crm/channelPartner-clone/",
    redirectUrl: "/crm/channelPartner",
    deleteUrl: "channel-partner-mass-delete",
    transferUrl: "channel-partner-mass-transfer",
    massUpdateUrl: "channel-partner-mass-update",
    excelUrl: "add-channel-partner-excel",
  },
};
export const list1 = [
  "Leads", "Contacts", "Accounts", "Opportunities", "Tasks", "Meeting", "Calls", "Sms", "Email", "Whatsapp", "siteVisit", "Inventory", "Note", "Quotes", "Invoice", "sale-orders", "Vendor", "channel-partner",
]

